"""create student languages table

Revision ID: abf0f3a1040c
Revises: a5e19aa41b64
Create Date: 2026-08-24 16:15:56.610225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf0f3a1040c'
down_revision: Union[str, Sequence[str], None] = 'a5e19aa41b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_languages',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'language_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_languages')
    # ### end Alembic commands ###
